// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using valkyrieIMS.Data;

namespace valkyrieIMS.Migrations
{
    [DbContext(typeof(valkyrieContext))]
    [Migration("20190616235408_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("valkyrieIMS.Data.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomerEmail");

                    b.Property<string>("CustomerFirstName");

                    b.Property<string>("CustomerLastName");

                    b.Property<string>("CustomerPhone");

                    b.Property<int?>("SaleReceiptId");

                    b.HasKey("CustomerId");

                    b.HasIndex("SaleReceiptId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("valkyrieIMS.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("ProductName");

                    b.Property<int?>("PurchaseInvoiceId");

                    b.Property<decimal>("PurchasePrice");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("SalePrice");

                    b.Property<int?>("SaleReceiptId");

                    b.Property<string>("Unit");

                    b.Property<string>("VendorName");

                    b.HasKey("ProductId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.HasIndex("SaleReceiptId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("valkyrieIMS.Data.Entities.PurchaseInvoice", b =>
                {
                    b.Property<int>("PurchaseInvoiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InvoiceDate");

                    b.Property<int?>("ProductNameProductId");

                    b.Property<decimal>("PurchasePrice");

                    b.Property<int>("Quantity");

                    b.Property<string>("VendorName");

                    b.HasKey("PurchaseInvoiceId");

                    b.HasIndex("ProductNameProductId");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("valkyrieIMS.Data.Entities.SaleReceipt", b =>
                {
                    b.Property<int>("SaleReceiptId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomerFirstName");

                    b.Property<string>("CustomerLastName");

                    b.Property<string>("ProductName");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("ReceiptDate");

                    b.Property<decimal>("SalePrice");

                    b.HasKey("SaleReceiptId");

                    b.ToTable("SaleReceipts");
                });

            modelBuilder.Entity("valkyrieIMS.Data.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PurchaseInvoiceId");

                    b.Property<string>("VendorAddress");

                    b.Property<string>("VendorEmail");

                    b.Property<string>("VendorName");

                    b.Property<string>("VendorPhone");

                    b.HasKey("VendorId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("valkyrieIMS.Data.Entities.Customer", b =>
                {
                    b.HasOne("valkyrieIMS.Data.Entities.SaleReceipt")
                        .WithMany("Customers")
                        .HasForeignKey("SaleReceiptId");
                });

            modelBuilder.Entity("valkyrieIMS.Data.Entities.Product", b =>
                {
                    b.HasOne("valkyrieIMS.Data.Entities.PurchaseInvoice")
                        .WithMany("Products")
                        .HasForeignKey("PurchaseInvoiceId");

                    b.HasOne("valkyrieIMS.Data.Entities.SaleReceipt")
                        .WithMany("Product")
                        .HasForeignKey("SaleReceiptId");
                });

            modelBuilder.Entity("valkyrieIMS.Data.Entities.PurchaseInvoice", b =>
                {
                    b.HasOne("valkyrieIMS.Data.Entities.Product", "ProductName")
                        .WithMany()
                        .HasForeignKey("ProductNameProductId");
                });

            modelBuilder.Entity("valkyrieIMS.Data.Entities.Vendor", b =>
                {
                    b.HasOne("valkyrieIMS.Data.Entities.PurchaseInvoice")
                        .WithMany("Vendors")
                        .HasForeignKey("PurchaseInvoiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
